#ifndef SIXTEEN_PARENT_PEDIGREE_RANDOM_FUNNELS_HEADER_GUARD
#define SIXTEEN_PARENT_PEDIGREE_RANDOM_FUNNELS_HEADER_GUARD
#include <Rcpp.h>
SEXP sixteenParentPedigreeRandomFunnels(SEXP initialPopulationSize_sexp, SEXP selfingGenerations_sexp, SEXP nSeeds_sexp, SEXP intercrossingGenerations_sexp);
#endif
