setMethod(f = "print", signature = "mpcross", definition = function(x)
{
  missingInFounders <- apply(x@founders, 2, function(y) any(is.na(y)))
  founderAlleles <- apply(x@founders, 2, function(y) length(unique(y)))
  nLines <- nLines(x)
  proportionMissing <- apply(x@finals, 2, function(y) sum(is.na(y)) / nLines)
  cat("-------------------------------------------------------\n")
  cat("Summary of mpcross object\n")
  cat("-------------------------------------------------------\n")
  cat(sum(missingInFounders), " markers had missing values in founders\n")
  cat(sum(founderAlleles==1), " markers had non-polymorphic founder genotypes\n")
  cat("-------------------------------------------------------\n")
  cat(sum(founderAlleles==2), " markers were biallelic.\n")
  cat(sum(founderAlleles > 2), " markers were multiallelic.\n")
  cat("-------------------------------------------------------\n")
  cat(sum(proportionMissing>.05), " markers had >5% missing data.\n")
  cat(sum(proportionMissing>.10), " markers had >10% missing data.\n")
  cat(sum(proportionMissing>.20), " markers had >20% missing data.\n")
  cat("-------------------------------------------------------\n")
  cat(length(which(segpval<1e-5)), " markers had <1e-5 p-value for segregation distortion\n")
  cat(length(which(segpval<1e-10)), " markers had <1e-10 p-value for segregation distortion\n")
  cat(length(which(segpval<1e-15)), " markers had <1e-15 p-value for segregation distortion\n")

})