#' @import qtl
#' @importFrom igraph plot.igraph V E "E<-" graph.empty vertices edges layout.reingold.tilford
#' @import methods
#' @import utils
#' @import ggplot2
#' @import graphics
#' @importFrom progress progress_bar
#' @importFrom graphics plot
#' @importFrom stats as.dist cutree pchisq rnorm cor manova na.omit
#' @importFrom utils combn head tail
#' @importFrom pryr address
#' @importFrom fastcluster hclust
#' @importFrom nnls nnls
#' @importFrom ggplot2 ggplot
#' @importFrom Heatplus heatmap_2
#' @importFrom RColorBrewer brewer.pal
#' @exportClass pedigreeGraph
#' @exportClass probabilities
#' @exportMethod subset 
#' @exportClass mpcross
#' @exportClass pedigreeGraph
#' @exportMethod imputationMap
#' @exportMethod plot
#' @exportMethod flatImputationMapNames
#' @importClassesFrom Matrix index dspMatrix dppMatrix
#' @importFrom methods setClass
#' @importFrom jsonlite toJSON
#' @useDynLib mpMap2
NULL

#' @name simulatedFourParentData
#' @title Simulated data from a four-parent population. 
#' @docType data
#' @description Simulated data from a four-parent population. Used in the examples given in the documentation.
#' @examples
#' #This data was generated by the following script
#' pedigree <- fourParentPedigreeRandomFunnels(initialPopulationSize = 1000,
#'      selfingGenerations = 6, intercrossingGenerations = 0)
#' #Assume infinite generations of selfing in subsequent analysis
#' selfing(pedigree) <- "infinite"
#' #Generate random map
#' map <- qtl::sim.map(len = 100, n.mar = 101, anchor.tel = TRUE, include.x = FALSE)
#' #Simulate data
#' simulatedFourParentData <- simulateMPCross(map = map, pedigree = pedigree, mapFunction = haldane, seed = 1L)
#' #save(simulatedFourParentData, map, file = "data/simulatedFourParentData.RData")
NULL
