#' @import qtl
#' @importFrom igraph plot.igraph V E "E<-" graph.empty vertices edges layout.reingold.tilford
#' @import methods
#' @import utils
#' @import ggplot2
#' @import graphics
#' @importFrom progress progress_bar
#' @importFrom graphics plot
#' @importFrom stats as.dist cutree pchisq rnorm cor manova na.omit
#' @importFrom utils combn head tail
#' @importFrom pryr address
#' @importFrom fastcluster hclust
#' @importFrom nnls nnls
#' @importFrom ggplot2 ggplot
#' @importFrom Heatplus heatmap_2
#' @importFrom RColorBrewer brewer.pal
#' @exportClass pedigreeGraph
#' @exportClass probabilities
#' @exportMethod subset 
#' @exportClass mpcross
#' @exportClass pedigreeGraph
#' @exportMethod imputationMap
#' @exportMethod plot
#' @exportMethod flatImputationMapNames
#' @importClassesFrom Matrix index dspMatrix dppMatrix
#' @importFrom methods setClass
#' @importFrom jsonlite toJSON
#' @importClassesFrom sn SECdistrMv
#' @importFrom stats lm contrasts<-
#' @importFrom sn dmst extractSECdistr selm
#' @importMethodsFrom sn plot
#' @importFrom igraph max_cliques graph_from_adjacency_matrix
#' @useDynLib mpMap2
NULL

#' @name simulatedFourParentData
#' @title Simulated data from a four-parent population. 
#' @rdname simulatedFourParentData
#' @docType data
#' @description Simulated data from a four-parent population. Used in the examples given in the documentation.
#' @examples
#' set.seed(1)
#' #This data was generated by the following script
#' pedigree <- fourParentPedigreeRandomFunnels(initialPopulationSize = 1000,
#'      selfingGenerations = 6, intercrossingGenerations = 0)
#' #Assume infinite generations of selfing in subsequent analysis
#' selfing(pedigree) <- "infinite"
#' #Generate random map
#' simulatedFourParentMap <- qtl::sim.map(len = 100, n.mar = 101, anchor.tel = TRUE, 
#' 	include.x = FALSE)
#' #Simulate data
#' simulatedFourParentData <- simulateMPCross(map = simulatedFourParentMap, pedigree = pedigree, 
#' 	mapFunction = haldane, seed = 1L)
#' #save(simulatedFourParentData, simulatedFourParentMap, file = "data/simulatedFourParentData.RData")
NULL
#' @name simulatedFourParentMap
#' @rdname simulatedFourParentData
NULL

#' @name eightWayExampleData
#' @title Example data from an 8-parent MAGIC population. 
#' @docType data
#' @author Alex Whan, Matthew Morell, Rohan Shah, Colin Cavanagh
#' This is a sample of 200 genetic markers from an 8-way MAGIC population of 4229 lines.
NULL
